### DO NOT EDIT THIS FILE ###

import solution
from tests import tests

passed = 0

for number, (description, test) in enumerate(tests, start=1):
    try:
        test(solution)

        print(f"✅ {number}. {description}")

        passed += 1

    except AssertionError as e:
        print(f"❌ {number}. {description}")

        print(e)

        break

print()
print(f"🎉 Congratulations! {passed}/{len(tests)} tests passed." if passed == len(tests) else f"{passed}/{len(tests)} tests passed.")