### DO NOT EDIT THIS FILE ###

import inspect

def assert_equal(actual, expected):
    assert actual == expected, (
        f"\nExpected:\n{expected}\n\nReceived:\n{actual}"
    )

def assert_parameter_count(func, count):
    params = inspect.signature(func).parameters

    assert len(params) == count, (
        f"{func.__name__}() should accept {count} parameter(s)."
    )

def test_dictionary_exists(solution):
    assert hasattr(solution, "test_settings"), (
        "Dictionary test_settings was not found."
    )

def test_add_setting_exists(solution):
    assert hasattr(solution, "add_setting"), (
        "Function add_setting() was not found."
    )

def test_add_setting_parameters(solution):
    assert_parameter_count(solution.add_setting, 2)

# def test_add_setting_lowercase(solution):
#     settings = {}

#     solution.add_setting(settings, ("THEME", "DARK"))

#     assert settings == { "theme": "dark" }

#     assert "theme" in settings, (
#         "The setting should be added using a lowercase key."
#     )

#     assert settings["theme"] == "dark", (
#         "The setting value should be stored in lowercase."
#     )

def test_add_setting_duplicate(solution):
    settings = {
        "theme": "light"
    }

    result = solution.add_setting(settings, ("THEME", "dark"))

    assert_equal(
        result,
        "Setting 'theme' already exists! Cannot add a new setting with this name."
    )

def test_add_setting_success(solution):
    settings = {
        "theme": "light"
    }

    result = solution.add_setting(settings, ("volume", "HIGH"))

    assert_equal(
        result, 
        "Setting 'volume' added with value 'high' successfully!"
    )

    assert settings == {
        "theme": "light",
        "volume": "high"
    }, (
        "Dictionary was not updated correctly."
    )

def test_update_setting_exists(solution):
    assert hasattr(solution, "update_setting"), (
        "Function update_setting() was not found."
    )

def test_update_setting_parameters(solution):
    assert_parameter_count(solution.update_setting, 2)

# def test_update_setting_lowercase(solution):
#     settings = {
#         "theme": "light"
#     }

#     solution.update_setting(settings, ("THEME", "DARK"))

#     assert settings == {"theme": "dark"}, (
#         "Keys and values should be converted to lowercase."
#     )

def test_update_setting_success(solution):
    settings = {
        "theme": "light"
    }

    result = solution.update_setting(
        settings,
        ("theme", "DARK")
    )

    assert_equal(result, "Setting 'theme' updated to 'dark' successfully!")

    assert settings["theme"] == "dark"

def test_update_setting_missing(solution):
    settings = {
        "theme": "light"
    }

    result = solution.update_setting(
        settings,
        ("volume", "high")
    )

    assert_equal(
        result, 
        "Setting 'volume' does not exist! Cannot update a non-existing setting."
    )

def test_delete_setting_exists(solution):
    assert hasattr(solution, "delete_setting"), (
        "Function delete_setting() was not found."
    )

def test_delete_setting_params(solution):
    assert_parameter_count(solution.delete_setting, 2)

# def test_delete_setting_lowercase(solution):
#     settings = {
#         "theme": "light"
#     }

#     solution.delete_setting(settings, "THEME")

#     assert settings == {}

def test_delete_setting_success(solution):
    settings = {
        "theme": "light"
    }

    result = solution.delete_setting(settings, "theme")

    assert_equal(
        result,
        "Setting 'theme' deleted successfully!"
    )
    assert settings == {}

def test_delete_setting_missing_key(solution):
    settings = {
        "theme": "light"
    }

    result = solution.delete_setting(
        settings, "notifications"
    )

    expected = (
        "Setting not found!"
    )

    assert result == expected

def test_view_settings_exists(solution):
    assert hasattr(solution, "view_settings"), (
        "Function view_settings() was not found."
    )

def test_view_settings_params(solution):
    assert_parameter_count(solution.view_settings, 1)

def test_view_settings_empty(solution):
    result = solution.view_settings({})

    assert result == "No settings available."

def test_view_settings_output(solution):
    settings = {
        "theme": "dark",
        "notifications": "enabled",
        "volume": "high"
    }

    expected = (
        "Current User Settings:\n"
        "Theme: dark\n"
        "Notifications: enabled\n"
        "Volume: high\n"
    )

    result = solution.view_settings(settings)

    assert result == expected


tests = [
    (
        "Dictionary test_settings exists",
        test_dictionary_exists
    ),

    (
        "add_setting exists",
        test_add_setting_exists
    ),

    (
        "add_setting has two parameters",
        test_add_setting_parameters
    ),

    # (
    #     "add_setting converts to lowercase",
    #     test_add_setting_lowercase
    # ),

    (
        "add_setting handles duplicates",
        test_add_setting_duplicate
    ),

    (
        "add_setting adds new setting",
        test_add_setting_success
    ),

    # update_settings tests
    (
        "update_setting exists",
        test_update_setting_exists
    ),

    (
        "update_setting has two parameters",
        test_update_setting_parameters
    ),

    # (
    #     "update_setting converts to lowercase",
    #     test_update_setting_lowercase
    # ),

    (
        "update_setting updates setting",
        test_update_setting_success
    ),

    (
        "update_setting handles missing key",
        test_update_setting_missing
    ),

    # delete_setting tests
    (
        "delete_setting exists",
        test_delete_setting_exists
    ),

    (
        "delete_setting has two parameters",
        test_delete_setting_params
    ),

    # (
    #     "delete_setting converts to lowercase",
    #     test_delete_setting_lowercase
    # ),

    (
        "delete_setting removes existing key",
        test_delete_setting_success
    ),

    (
        "delete_setting handles missing key",
        test_delete_setting_missing_key
    ),

    # view_setting tests...
    (
        "view_settings exists",
        test_view_settings_exists
    ),

    (
        "view_settings has one parameter",
        test_view_settings_params
    ),

    (
        "view_settings empty",
        test_view_settings_empty
    ),

    (
        "view_settings output",
        test_view_settings_output
    ),
]